### ISSUE TITLE
Question about ablation of 4D decomposed hash encoding

### ISSUE THREAD

**Issue by tb2-sy** [JiaweiXu8/Grid4D#1]
Thanks for your nice work! The ablation study of 4D decomposed hash encoding mentioned the results of using simple 4D hyper-grid hash encoding. My question is that according to the coordinate conflict claimed in Figure 2, shouldn’t this representation be completely free of feature overlap?

**Comment by JiaweiXu8** [comment]
Sorry for the delayed reponse, and thanks for your interest. We think there might be two main reasons for the degradation of the simple 4D hyper-grid hash encoding.
+ High hash collision. As memtioned in the Section 3.2 of our paper and Section 3.2 of [1], the space complexity of 4D hyper-grid requires $O(n^4)$, which might lead to the degradation. This problem might be more obvious in handling larger scenes.
+ The indiscriminable treatment of spatial and temporal encodings. To our knowledge, the simple 4D hyper-grid has no ability to get the individual spatial and temporal features. However, the spatial and temporal features might have different properties in dynamic scene tasks, which need different processing.

Hoping the above answer can be helpful.

[1] FengWang, Zilong Chen, GuokangWang, Yafei Song, and Huaping Liu. Masked space-time hash encoding
for efficient dynamic scene reconstruction. Advances in Neural Information Processing Systems, 2023.

**Comment by tb2-sy** [comment]
Thanks for your reply and clarification!
