### ISSUE TITLE
Question about the d_xyz?

### ISSUE THREAD

**Issue by chenj02** [JiaweiXu8/Grid4D#4]
In your paper, the d_xyz is defined by [R] and [T], why not just deformed as [dx, dy, dz]?

**Comment by CTouch** [comment]
I have the same question. I think the effect of $\bar X'=R_x \bar X + T_x$ is equal to the effect of $\bar X'=\bar X + T_x$. And the $R+\Delta r$ seems strange.
Did you figure it out ?
![image](https://github.com/user-attachments/assets/04e599b4-0d87-4d83-a4ac-3941fd11d2b2)

**Comment by chenj02** [comment]
> I have the same question. I think the effect of X ¯ ′ = R x X ¯ + T x is equal to the effect of X ¯ ′ = X ¯ + T x . And the R + Δ r seems strange. Did you figure it out ? ![image](https://private-user-images.githubusercontent.com/65765708/388877483-04e599b4-0d87-4d83-a4ac-3941fd11d2b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MTU0MjEsIm5iZiI6MTczMjcxNTEyMSwicGF0aCI6Ii82NTc2NTcwOC8zODg4Nzc0ODMtMDRlNTk5YjQtMGQ4Ny00ZDgzLWE0YWMtMzk0MWZkMTFkMmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDEzNDUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MTdhMWEwNTg2MzJhNmVlY2Y0MDAzOGE5ZmI1NDIzOWEyYjU4ZjIxZGIyZGFlMWNkYjkzMzg2N2Q4YmY3NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MVn9nBBrJuCM1CyiBhpeQCyDuhzj9epbeHWfkxGXDw4)

Hello, I have try to train with [dx, dy, dz], and the results are almost the same as the method by [R] and [T]

**Comment by CTouch** [comment]
Got it! thanks!
