### ISSUE TITLE
There seems to be a case of a cuda memory leak at "render.py"

### ISSUE THREAD

**Issue by CTouch** [JiaweiXu8/Grid4D#5]
``` bash
CUDA_VISIBLE_DEVICES=1 python render.py --conf ./arguments/neu3d/flame_salmon_1.py -m output/N3DV/1202/flame_salmon_1202
```

I met the `Cuda out-of memory` when running `render.py` rendering `neu3d` dataset for abount 2000 images. And I noticed that the GPU-Memory usage continues to rise. 
Does anybody have the same problem? I am tring to figure it out.

**Comment by CTouch** [comment]
https://github.com/JiaweiXu8/Grid4D/blob/a8992a9bd18b1828d2890a190421bca8bf0d2e80/render.py#L41

Because the `view` is loaded to GPU without release.

**Comment by Next11111** [comment]
<img width="1823" height="656" alt="Image" src="https://github.com/user-attachments/assets/f4ca4e41-025a-4f5a-bcab-952e1bea0095" />如何解决呢？
